# -*- coding: utf-8 -*-
"""Translate project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DeqKkLUTLMDpEhZdbDwJtt1OlBwibeqK
"""

pip install googletrans==4.0.0-rc1

from googletrans import Translator

def translate_text(text, source_language, target_language):
    translator = Translator()
    translated_text = translator.translate(text, src=source_language, dest=target_language)
    return translated_text.text

def main():
    source_language = 'en'  # English
    target_language = 'es'  # Spanish

    text_to_translate = "Hello, my name vijay?"

    translated_text = translate_text(text_to_translate, source_language, target_language)
    print(f"Translated: {translated_text}")

if __name__ == "__main__":
    main()